### ISSUE TITLE
Is web scraping the best choice?

### ISSUE THREAD

**Issue by pjohnmeyer** [SharpeLombard/liftoff-assignments#2]
It is not a best-practice of web development to base an app off of scraped data. Additionally, we want to be mindful of violating any terms of service, or legal violations around storing data not owned by or licensed to us.

Perhaps we can find some APIs to use instead? Let's put our heads together on this.

**Comment by SharpeLombard** [comment]
After thinking about it and discussing, I think I will include links to other APIs as well as populate the database on my own.
